<a href="https://colab.research.google.com/github/SeongwonTak/RecommenderSystem/blob/main/Basic_code_Recom_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recommender System 기초 구현

## 기본 준비 및 전처리

https://lsjsj92.tistory.com/565 를 따라하며 구현을 실습한다.

물론, 거기에 직접 일부 부분 / 추가로 실험하고 싶은 부분은 추가 실험을 해 보기로 한다.

예를 들어, neighborhood를 확인할 때, 다른 metric을 부여한다던가.

사용하는 Dataset은 영화 관련 Dataset이다.
https://www.kaggle.com/rounakbanik/the-movies-dataset

In [1]:
# 패키지를 먼저 import 한다. 추가로 필요한 패키지는 그때그때.
import numpy as np
import pandas as pd
import sklearn as sk

In [57]:
# Step 0. 데이터를 불러온다.
movie_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RecoExample/movies_metadata.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [58]:
movie_data.tail(5)

adult belongs_to_collection budget  ...  video vote_average vote_count
45461  False                   NaN      0  ...  False          4.0        1.0
45462  False                   NaN      0  ...  False          9.0        3.0
45463  False                   NaN      0  ...  False          3.8        6.0
45464  False                   NaN      0  ...  False          0.0        0.0
45465  False                   NaN      0  ...  False          0.0        0.0

[5 rows x 24 columns]

우선은 영화의 Meta data들부터 분석하려고 한다.
여러 변수들이 있는데, 사용할 변수를 추리기 위해 우선은 변수들을 정리한다.
- id : 영화 번호
- title : 영화 제목
- genres : 영화 장르
- popularity : 영화 인기도
- vote_average : 평균 평점
- vote_count : 평점 매긴 사람의 수
- release_date : 영화 발매일
- adult : 말 그대로, 성인영화인가?
- overview : 개요

이정도만 사용하려고 한다.

In [59]:
movie_data = movie_data[['id','title', 'genres', 'popularity', 'vote_average', 'vote_count', 'release_date', 'adult', 'overview']]

각 항목들에 대해서 전처리를 실시해야 한다.

In [60]:
movie_data.tail(5)

id  ...                                           overview
45461  439050  ...        Rising and falling between a man and woman.
45462  111109  ...  An artist struggles to finish his work while a...
45463   67758  ...  When one of her hits goes wrong, a professiona...
45464  227506  ...  In a small town live two brothers, one a minis...
45465  461257  ...  50 years after decriminalisation of homosexual...

[5 rows x 9 columns]

장르를 의미있게 활용하기 위해,keyword를 별도로 부른 후 keyword를 movie_data와 연결하려고 한다.

In [61]:
keywords = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RecoExample/keywords.csv')

In [62]:
keywords.tail()

id                                           keywords
46414  439050             [{'id': 10703, 'name': 'tragic love'}]
46415  111109  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...
46416   67758                                                 []
46417  227506                                                 []
46418  461257                                                 []

In [63]:
# 타입을 통일시켜서 붙일 것이다.
# 후에 문자열 전처리 도구를 사용할것이기에, string 변경.
movie_data.id = movie_data.id.astype(str)
keywords.id = keywords.id.astype(str)
movie_combined = pd.merge(movie_data, keywords)

In [64]:
movie_combined.tail()

id  ...                                           keywords
46477  439050  ...             [{'id': 10703, 'name': 'tragic love'}]
46478  111109  ...  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...
46479   67758  ...                                                 []
46480  227506  ...                                                 []
46481  461257  ...                                                 []

[5 rows x 10 columns]

우선 먼저 결측치부터 정리하려고 한다.

In [ ]:
movie_combined.isnull().sum()

id                0
genres            0
popularity        4
vote_average      4
vote_count        4
release_date     88
adult             0
overview        995
keywords          0
dtype: int64

In [65]:
movie_combined = movie_combined.dropna(axis=0, how='any')

In [ ]:
movie_combined.tail()

id  ...                                           keywords
46476   30840  ...                                                 []
46478  111109  ...  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...
46479   67758  ...                                                 []
46480  227506  ...                                                 []
46481  461257  ...                                                 []

[5 rows x 9 columns]

Index가 꼬여 있으면 영 좋지 않다. index를 정리해주자.

In [66]:
movie_combined.reset_index(inplace = True, drop = True)

In [ ]:
movie_combined.tail()

id  ...                                           keywords
45407   30840  ...                                                 []
45408  111109  ...  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...
45409   67758  ...                                                 []
45410  227506  ...                                                 []
45411  461257  ...                                                 []

[5 rows x 9 columns]

또한 다음 데이터들도 버려야 할 것이다.
- genres가 없는 데이터들
- vote_count가 0인 것들(... 왜 있어?)
- keywords가 없는 것들

In [67]:
# 사고대비
movie_backup = movie_combined.copy()

In [ ]:
movie_backup.dtypes

id               object
genres           object
popularity       object
vote_average    float64
vote_count      float64
release_date     object
adult            object
overview         object
keywords         object
dtype: object

In [68]:
movie_backup = movie_backup.loc[movie_backup['vote_count']>0,:]

In [69]:
movie_backup = movie_backup.loc[movie_backup['keywords'] != '[]',:]
movie_backup = movie_backup.loc[movie_backup['genres'] != '[]',:]

In [11]:
movie_backup

id  ...                                           keywords
0         862  ...  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1        8844  ...  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2       15602  ...  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3       31357  ...  [{'id': 818, 'name': 'based on novel'}, {'id':...
4       11862  ...  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...
...       ...  ...                                                ...
45400  404604  ...  [{'id': 155794, 'name': 'physical abuse'}, {'i...
45403   84419  ...  [{'id': 9748, 'name': 'revenge'}, {'id': 9826,...
45404  390959  ...            [{'id': 224180, 'name': 'blair witch'}]
45405  289923  ...  [{'id': 616, 'name': 'witch'}, {'id': 2035, 'n...
45408  111109  ...  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...

[29902 rows x 9 columns]

In [70]:
movie_combined = movie_backup
movie_combined.reset_index(inplace = True, drop = True)

위의 과정에서 부딪힌 문제 상황은 다음과 같다
- genres와 keywords를 list화 시켜야 한다.
ast 패키지의 literal_eval을 활용할 수 있다.

In [71]:
import ast
movie_combined['genres'] = movie_combined['genres'].apply(ast.literal_eval)

In [72]:
movie_combined['keywords'] = movie_combined['keywords'].apply(ast.literal_eval)

이제 구조를 자세히 보면, list내 각 dict의 name에 있는 것을 다시 list화 시켜야 함을 알 수 있다.

In [73]:
movie_combined['genres'] = movie_combined['genres'].apply(lambda x: [d['name'] for d in x]).apply(lambda x: " ".join(x))

In [74]:
movie_combined['keywords'] = movie_combined['keywords'].apply(lambda x: [d['name'] for d in x]).apply(lambda x: " ".join(x))

In [17]:
movie_combined

id  ...                                           keywords
0         862  ...  jealousy toy boy friendship friends rivalry bo...
1        8844  ...  board game disappearance based on children's b...
2       15602  ...   fishing best friend duringcreditsstinger old men
3       31357  ...  based on novel interracial relationship single...
4       11862  ...  baby midlife crisis confidence aging daughter ...
...       ...  ...                                                ...
29897  404604  ...                      physical abuse sexual assault
29898   84419  ...  revenge murder serial killer new york city scu...
29899  390959  ...                                        blair witch
29900  289923  ...  witch mythology legend serial killer mockumentary
29901  111109  ...                                  artist play pinoy

[29902 rows x 9 columns]

다음은 평점에 대해 전처리를 실시하려고 한다.
평점에 대한 전처리를 하는 이유는 인원수에 대한 편차를 줄이기 위함이다.
https://www.quora.com/How-does-IMDbs-rating-system-work

를 기준으로 하여 평점을 변경해보자.

- R : 특정 영화의 평균 평점
- V : 특정 영화의 투표 수
- C : 전체 영화의 평균 평점
- M : 특정 등수(여기서는 약 상위 10%인 3000위정도로 하자.)에 들기 위한 최소 요구 투표수.

산식은

$$ \frac{V}{V+M} \times R + \frac{M}{V+M} \times C $$ 으로 주어진다.

각 값들을 구해보자.

In [75]:
# C 구하기.
C = movie_combined['vote_average'].mean()
C

6.052330947762581

In [76]:
# M 구하기
# 0.9분위수로 충분하다
M = movie_combined['vote_count'].quantile(0.9)
M

302.0

In [77]:
def weight_rate(x, m=M, c=C):
  # 행별로 들어갈 함수
  V = x['vote_count']
  R = x['vote_average']

  return (V / (V + m) * R) + (m / (m + V) * c)

In [78]:
movie_combined['adj_score'] = movie_combined.apply(weight_rate, axis = 1)

In [98]:
movie_combined.head(10)

id  ... adj_score
0    862  ...  7.612962
1   8844  ...  6.805710
2  15602  ...  6.156863
3  31357  ...  6.057155
4  11862  ...  5.924008
5    949  ...  7.472580
6  11860  ...  6.099332
7   9091  ...  5.850428
8    710  ...  6.489441
9   9087  ...  6.230148

[10 rows x 11 columns]

## Content-based Model의 구현

가장 먼저 할 일은 Content-based Model에 대한 구현이다.
장르 기준으로 추천 모델을 짜보려고 한다.
- 유사도가 높을수록 먼저 추천
- 동일한 유사도일 경우 Adj_score가 더 높은 아이템을 추천한다.

먼저 장르가 현재 어떻게 생겨먹었나를 보자.

In [27]:
movie_combined.genres.head(10)

0        Animation Comedy Family
1       Adventure Fantasy Family
2                 Romance Comedy
3           Comedy Drama Romance
4                         Comedy
5    Action Crime Drama Thriller
6                 Comedy Romance
7      Action Adventure Thriller
8      Adventure Action Thriller
9           Comedy Drama Romance
Name: genres, dtype: object

우리가 원하는 짓은 여기 있는 단어들을 하나하나 열로 만들어서 vector화 시키고 싶은 것이다. 

문제중 하나는 저 많은 영화 데이터에 얼마나 많은 장르가 담겨있는지 알기가 어렵고, 길이도 제마다 달라 추출이 어렵다. 집합을 사용하여 하나하나 빼는 방법도 있겠으나, 다른 방법을 써보자.

### CountVectorizer

Scikit-learn에 있는 기능을 하나 가져와보자.
하려는 행동은, 각 줄에 들어가있는 단어들이 몇 개인지 세는 것이다. 

즉, movie-genre matrix의 생성이다.
**즉 어떤 영화가 특정 장르에 속하면 1, 아니면 0을 반환하는 행렬을 만들어주면 된다.**
이를 CountVectorzier를 통해 생성해 줄 수 있다.


In [79]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
cnt_genres = count_vector.fit_transform(movie_combined['genres'])
genres_matrix = cnt_genres.toarray()

In [80]:
print(genres_matrix)

[[0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [81]:
#column별 의미 추출
print(count_vector.vocabulary_)

{'animation': 2, 'comedy': 3, 'family': 7, 'adventure': 1, 'fantasy': 8, 'romance': 16, 'drama': 6, 'action': 0, 'crime': 4, 'thriller': 18, 'horror': 12, 'history': 11, 'science': 17, 'fiction': 9, 'mystery': 15, 'war': 20, 'foreign': 10, 'music': 14, 'documentary': 5, 'western': 21, 'tv': 19, 'movie': 13}


### Similarity
이제 위의 결과물로 유사도를 활용하여 추천 모델을 만들어보자.



목표는 다음과 같다. 

1. 영화-영화간의 유사도를 구하자.
2. 특정 영화 제목이 주어질 때, 유사도가 가장 높은 영화 10개를 선정한다.

우리가 사용할 유사도는 다양한 것들 중 cosine similarity를 사용할려고 한다.
말 그대로, cosine값을 주려고 한다.

In [82]:
def cosine_similarity(a, b):
  norm_a = np.linalg.norm(a, ord = 2)
  norm_b = np.linalg.norm(b, ord = 2)
  return np.dot(a, b) / (norm_a * norm_b)
# 사실은 scikit-learn에 패키지가 있으나, 직접 만들었다.

In [83]:
genres_matrix.shape[0]

29902

즉 29,902개의 영화 중 제목이 일치하는 것을 하나 잡은 후, 제목이 일치하는 인덱스를 뽑아야 한다.

In [99]:
target_title = str(input())
target_index = movie_combined[movie_combined['title'] == target_title].index.values[0]
print(target_index)
target_sim = [0 for _ in range(29902)]
for i in range(29902):
  if i == target_index:
    target_sim[i] = 0
  else:
    target_sim[i] = cosine_similarity(genres_matrix[i], genres_matrix[target_index])

result_sim_df = pd.DataFrame(data = target_sim, index = range(29902), columns=['sim'])
result = pd.concat([movie_combined, result_sim_df], axis = 1)
final_result = result.sort_values('sim', ascending=False)[:10]['title']
print(final_result)

Jumanji
1
10535                       The Spiderwick Chronicles
25714                      Kingdom of Crooked Mirrors
1696                                     Return to Oz
13280    Harry Potter and the Deathly Hallows: Part 1
21104                                             Pan
28242                                            Mama
26786                                   Pete's Dragon
22023         Fantastic Beasts and Where to Find Them
12400                             Alice in Wonderland
28158                     Adventures in Dinosaur City
Name: title, dtype: object


다만, 이렇게 설계할 경우 아쉬운 점은 실제 영화의 평점 등은 전혀 반영되지 않았다는 점이다. 오로지 '장르의 유사성'에만 집중하여 영화의 추천이 일어났다.
다만, 이번 구현에서는 가장 원론적인 구현 방법론에만 집중하려 한다.

## Collaborative-Filtering의 구현

Matrix Factorization 이전에, 