<a href="https://colab.research.google.com/github/SeongwonTak/RecommenderSystem/blob/main/Recommendation_with_MatrixFactorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recommendation_with_MatrixFactorization
https://lsjsj92.tistory.com/569?category=853217
을 기반으로 따라 실습해보았다.




## 데이터셋 준비.
영화 관련 데이터를 가져오려 한다.
평점과 제목만 있으면 된다.

In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

In [2]:
movie_data_raw = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RecoExample/movies_metadata.csv')
movie_ratings = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RecoExample/ratings_small.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
movie_data_raw.head()

adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0
3  False  ...       34.0
4  False  ...      173.0

[5 rows x 24 columns]

In [3]:
movie_data = movie_data_raw[['id', 'title']]
movie_data.rename(columns={"id":"movieId"}, inplace = True)
movie_data

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


movieId                        title
0         862                    Toy Story
1        8844                      Jumanji
2       15602             Grumpier Old Men
3       31357            Waiting to Exhale
4       11862  Father of the Bride Part II
...       ...                          ...
45461  439050                       Subdue
45462  111109          Century of Birthing
45463   67758                     Betrayal
45464  227506             Satan Triumphant
45465  461257                     Queerama

[45466 rows x 2 columns]

In [ ]:
movie_ratings.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [4]:
movie_ratings.drop('timestamp', axis = 1, inplace=True)

두 데이터를 합치려고 한다.

In [ ]:
movie_ratings.movieId = movie_ratings.movieId.astype('str')
movie_data.movieId = movie_data.movieId.astype('str')
user_movie_rating = pd.merge(movie_ratings, movie_data, on = 'movieId')
user_movie_rating

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


userId movieId  rating              title
0           1    1371     2.5          Rocky III
1           4    1371     4.0          Rocky III
2           7    1371     3.0          Rocky III
3          19    1371     4.0          Rocky III
4          21    1371     3.0          Rocky III
...       ...     ...     ...                ...
44989     652  129009     4.0     Love Is a Ball
44990     653    2103     3.0            Solaris
44991     659     167     4.0              K-PAX
44992     659     563     3.0  Starship Troopers
44993     665     129     3.0      Spirited Away

[44994 rows x 4 columns]

In [ ]:
user_movie_pivot = user_movie_rating.pivot_table('rating',
                                                 index='userId',
                                                 columns='title').fillna(0)

In [ ]:
user_movie_pivot.head()

title   !Women Art Revolution  'Gator Bait  ...  Ödipussi  Şaban Oğlu Şaban
userId                                      ...                            
1                         0.0          0.0  ...       0.0               0.0
2                         0.0          0.0  ...       0.0               0.0
3                         0.0          0.0  ...       0.0               0.0
4                         0.0          0.0  ...       0.0               0.0
5                         0.0          0.0  ...       0.0               0.0

[5 rows x 2794 columns]

In [ ]:
movie_user_pivot = user_movie_pivot.values.T

In [ ]:
user_movie_pivot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## SVD 적용
scikit-learn에는 다행히 이미 SVD가 구현되어 있다. 이를 적용하자.

In [ ]:
from sklearn.decomposition import TruncatedSVD
SVD = TruncatedSVD(n_components = 12)
matrix = SVD.fit_transform(movie_user_pivot)
matrix.shape

(2794, 12)

In [ ]:
corr = np.corrcoef(matrix)

movie_title = user_movie_pivot.columns
movie_title_list = list(movie_title)
coffey_hands = movie_title_list.index('Toy Story')
corr_coffey_hands = corr[coffey_hands]
list(movie_title[(corr_coffey_hands >= 0.9)])[:50]

## Matrix_Factorization을 활용한 사용자 기반 추천 구현

한편으로는 Matrix Factorization을 활용하여 사용자 기반 추천 또한 구현이 가능하다.

SVD 추천을 위해 먼저 user iD별 추천한 영화 데이터를 표로 만들어야 한다. 이는 pivot화로 가능하다.

In [ ]:
# 사용 데이터 재점검
movie_ratings.head()

userId movieId  rating
0       1      31     2.5
1       1    1029     3.0
2       1    1061     3.0
3       1    1129     2.0
4       1    1172     4.0

In [5]:
# Pivot 정의
df_user_movie_ratings = movie_ratings.pivot(
    index = 'userId',
    columns = 'movieId',
    values = 'rating'
).fillna(0)

In [ ]:
df_user_movie_ratings.head()

movieId    1   10  100  100017  100032  ...  99846  999  99912  99917  99992
userId                                  ...                                 
1        0.0  0.0  0.0     0.0     0.0  ...    0.0  0.0    0.0    0.0    0.0
2        0.0  4.0  0.0     0.0     0.0  ...    0.0  0.0    0.0    0.0    0.0
3        0.0  0.0  0.0     0.0     0.0  ...    0.0  0.0    0.0    0.0    0.0
4        0.0  4.0  0.0     0.0     0.0  ...    0.0  0.0    0.0    0.0    0.0
5        0.0  0.0  0.0     0.0     0.0  ...    0.0  0.0    0.0    0.0    0.0

[5 rows x 9066 columns]

SVD를 적용하기 전 user간의 bias를 보정하기 위해 mean-centered를 활용할 것이다.

mean-centered의 적용은 간단하게, user별로 평균 평점을 빼주면 된다.

In [6]:
matrix = np.matrix(df_user_movie_ratings)
user_ratings_mean = np.mean(matrix, axis = 1)
matrix_user_mean = matrix - user_ratings_mean.reshape(-1, 1)

In [ ]:
matrix

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 4., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [4., 0., 0., ..., 0., 0., 0.],
        [5., 0., 0., ..., 0., 0., 0.]])

In [7]:
pd.DataFrame(matrix_user_mean, columns = df_user_movie_ratings.columns).head()

movieId    1         2         3       ...    162542    162672    163949
0       -0.005625 -0.005625 -0.005625  ... -0.005625 -0.005625 -0.005625
1       -0.029230 -0.029230 -0.029230  ... -0.029230 -0.029230 -0.029230
2       -0.020075 -0.020075 -0.020075  ... -0.020075 -0.020075 -0.020075
3       -0.097838 -0.097838 -0.097838  ... -0.097838 -0.097838 -0.097838
4       -0.043128 -0.043128  3.956872  ... -0.043128 -0.043128 -0.043128

[5 rows x 9066 columns]

U, Sigma V를 얻기 위해 Scikit-learn에서 쓰는 SVD가 아닌, **scipy의 SVD**를 사용하자.

Remark. Scikit-learn 에서는 U, sigma, V를 얻을 수 없다.

In [8]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(matrix_user_mean, k = 12)

In [9]:
sigma

array([105.72437051, 110.15522471, 116.29714259, 118.66831462,
       122.82232277, 135.96585855, 138.92664501, 145.53348705,
       160.48685586, 199.93327534, 242.13488251, 462.13504865])

문제는, sigma는 대각행렬 형태로 나와야 하는데 그렇지가 않다. 이를 변형해줘야 한다.

In [10]:
sigma = np.diag(sigma)
sigma

array([[105.72437051,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        , 110.15522471,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        , 116.29714259,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , 118.66831462,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        122.82232277,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,

분해가 되었기에, 이제 다시 원본 행렬로 복구한다.
따라서 내적으로 U, sigma, Vt를 순서대로 곱해준 후 맨 마지막에 평균을 다시 더해서 복구한다.

In [11]:
svd_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)

In [12]:
df_svd_preds = pd.DataFrame(svd_user_predicted_ratings, columns = df_user_movie_ratings.columns)
df_svd_preds

movieId    1         2         3       ...    162542    162672    163949
0       -0.079686  0.021779 -0.013837  ... -0.005575 -0.005297 -0.003766
1        1.428452  1.608841  0.529476  ... -0.000957 -0.000753  0.026901
2        0.977246  0.396971  0.000299  ...  0.014637  0.013287 -0.005741
3        1.870844  1.169993  0.252202  ... -0.019365 -0.017113  0.066559
4        1.182777  0.924903  0.075998  ... -0.024027 -0.024614 -0.032752
..            ...       ...       ...  ...       ...       ...       ...
666      1.577140  1.002294  0.699893  ... -0.003929 -0.003212  0.000658
667      0.405596  0.011198  0.022474  ...  0.005298  0.005562 -0.014007
668      0.360704 -0.000016  0.086261  ... -0.001340 -0.001189 -0.004946
669      1.054516  0.265079  0.223782  ...  0.005344  0.004928 -0.008484
670      2.748977  0.189540  0.186176  ...  0.020446  0.018615 -0.019429

[671 rows x 9066 columns]

Data 준비가 완료되었다.

이제 실제 추천 시스템을 만들고자 한다. 다음 기능을 반영한다.
- 사용자가 보지 않은 영화중에서 평점이 높은 것을 추천하자.
- 단, 위에서 사용한 SVD를 기준으로 한다.

In [16]:
def recommend_movies(df_svd_preds, user_id,
                     ori_movies_df, ori_ratings_df, num_recommendations = 5):
  user_row_number = user_id - 1
  sorted_user_predictions = df_svd_preds.iloc[user_row_number].sort_values(ascending = False)
  user_data = ori_ratings_df[ori_ratings_df.userId == user_id]
  user_history = user_data.merge(ori_movies_df, on = 'movieId').sort_values(['rating'], ascending = False)
  recommendations = ori_movies_df[~ori_movies_df['movieId'].isin(user_history['movieId'])]
  recommendations = recommendations.merge(pd.DataFrame(sorted_user_predictions).reset_index(), on = 'movieId')
  recommendations = recommendations.rename(columns = {user_row_number: 'Predictions'}).sort_values('Predictions', ascending = False).iloc[:num_recommendations, :]
  return user_history, recommendations

In [ ]:
already_rated, predictions = recommend_movies(df_svd_preds, 330, movie_data, movie_ratings, 10)

In [ ]:
predictions